In [1]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

WARNING:tensorflow:From c:\Users\goggl\ANN Example\venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

### Loading everything
- [x] trained model
- [x] scaler pickle
- [x] one hot encoder pickle

In [2]:
model = load_model('model.h5') #loading the model

WARNING:tensorflow:From c:\Users\goggl\ANN Example\venv\Lib\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

In [10]:
with open('Label_encoder_gender.pkl', 'rb') as file:  #loading Geoencoder
    Label_encoder_gender = pickle.load(file)

with open('ohe_geo.pkl', 'rb') as file:  #loading Geography one hot encoder
    ohe_geo = pickle.load(file)

with open('scaler.pkl', 'rb') as file: #loding scaler
    scaler  = pickle.load(file)

In [4]:
input_data = {

'CreditScore':600,
'Geography':'France',
'Gender': 'Male',
'Age': 40,
'Tenure': 3,
'Balance': 60000,
'NumOfProducts': 2,
'HasCrCard': 1,
'IsActiveMember': 1,
'EstimatedSalary': 50000

}

In [20]:
geo_encoded = ohe_geo.transform([[input_data['Geography']]]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns = ohe_geo.get_feature_names_out())

c:\Users\goggl\ANN Example\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [ ]:
input_df = pd.DataFrame([input_data])
input_df

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [25]:
input_df['Gender'] = Label_encoder_gender.transform(input_df['Gender'])

In [27]:
input_df = pd.concat([input_df.drop('Geography', axis=1), geo_encoded_df], axis=1)

KeyError: "['Geography'] not found in axis"

In [28]:
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [30]:
input_scaled = scaler.transform(input_df)
input_scaled

array([[-0.52094729,  0.91163733,  0.10412869, -0.70623193, -0.26114949,
         0.80234676,  0.64978629,  0.97311137, -0.87017372,  0.99875078,
        -0.57658047, -0.57715782]])

In [31]:
prediction = model.predict(input_scaled)
prediction

1/1 [==============================] - 0s 92ms/step

array([[0.04607182]], dtype=float32)

In [34]:
prediction_prob = prediction[0][0]
if prediction_prob > 0.5:
    print('Customer is likely to churn')
else:
    print('Customer is not likely to churn')

Customer is not likely to churn